version: '3'
services:
  full-text-rss:
    image: aaronlee/full-text-rss:latest
    restart: always
    container_name: full-text-rss
    ports:
      - 8080:80
    volumes:
      - ./config/site-specific.sh:/home/www/site-specific.sh
      - ./config/custom_config.php:/home/www/custom_config.php
      - ./site:/var/www/html/site_config
