version: '3'
services:
  full-text-rss:
    image: aaronlee/full-text-rss:latest
    restart: always
    container_name: full-text-rss
    ports:
      - 8080:80
    volumes:
      - ./local/site:/var/www/html/site_config
      - ./local/cache:/var/www/html/cache
